Add home page for Linux Consumption app
sanchitmehta/KuduLight pull request #138
Opened 2020-10-07 01:41 UTC by Hazhzeng

1. Add homepage for Linux Consumption (Only exposing api/settings, and api/deployments)
![image](https://user-images.githubusercontent.com/48038149/95277676-3611ea80-0803-11eb-8df5-93f1ef1f4621.png)
2. Change Kudu.Core.Environment.IsOnLinuxConsumption to static, since it derives from environment variables.
3. Fix kudulite commit path to `https://github.com/Azure-App-Service/KuduLite/commit/<sha>`, (previously incorrectly pointed to `https://github.com/ProjectKudu/Kudu/commit/<sha>`).

cc: @balag0

2020-10-07 01:41 UTC, Hazhzeng commented
@sanchitmehta Please review, thanks \o/

2020-10-07 04:29 UTC, balag0 requested changes

2020-10-07 04:29 UTC, balag0 commented on Kudu.Core/Environment.cs
> +        public static bool IsOnLinuxConsumption
Is it possible to keep this non-static. (makes writing tests easier)

2020-10-07 04:29 UTC, balag0 commented on Kudu.Services.Web/Pages/Index.cshtml
> +        @if (!Kudu.Core.Environment.IsOnLinuxConsumption)
does cshtml support creating partial views (one for consumption and another for dedicated) to keep the logic isolated and reduce the ifs in this file.

2020-10-07 04:29 UTC, balag0 commented on Kudu.Services.Web/Pages/_Layout.cshtml
> +                @if (!Kudu.Core.Environment.IsOnLinuxConsumption)
similar comment as index.cshtml. possibility of partial views?

2020-10-07 04:29 UTC, balag0 commented on Kudu.Services/LinuxConsumptionInstanceAdmin/LinuxConsumptionRouteMiddleware.cs
>          private bool IsRouteWhitelisted(PathString routePath)
nit: rename to IsRouteAllowed

2020-10-07 04:29 UTC, balag0 commented on Kudu.Services/LinuxConsumptionInstanceAdmin/LinuxConsumptionRouteMiddleware.cs
>              return _whitelistedPathString.Any((ps) => routePath.StartsWithSegments(ps));
nit: rename to _allowedPaths

2020-10-08 20:12 UTC, sanchitmehta commented
LGTM!

2020-10-08 20:12 UTC, sanchitmehta approved these changes

2020-10-10 03:38 UTC, merged